# Generated by Django 5.2.7 on 2025-10-29 17:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Aumento'), ('decrease', 'Disminución')], max_length=10, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Cantidad')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='productos.productpresentation', verbose_name='Presentación')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventario.warehouse', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Cantidad')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Reservado')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Mínimo')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Máximo')),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Punto de Reorden')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='productos.productpresentation', verbose_name='Presentación')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventario.warehouse', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Item de Stock',
                'verbose_name_plural': 'Items de Stock',
                'indexes': [models.Index(fields=['warehouse', 'presentation'], name='inventario__warehou_773c43_idx'), models.Index(fields=['is_active'], name='inventario__is_acti_1a9b4b_idx')],
                'unique_together': {('warehouse', 'presentation')},
            },
        ),
    ]
