# Generated by Django 5.2.7 on 2025-10-29 17:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KardexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjust', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Referencia')),
                ('reference_type', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Referencia')),
                ('qty_in', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Cantidad Entrada')),
                ('qty_out', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Cantidad Salida')),
                ('balance_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Saldo Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=15, verbose_name='Costo Unitario')),
                ('movement_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Costo del Movimiento')),
                ('average_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=15, verbose_name='Costo Promedio')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_entries', to='productos.productpresentation', verbose_name='Presentación')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_entries', to='inventario.warehouse', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Entrada de Kardex',
                'verbose_name_plural': 'Entradas de Kardex',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['presentation', 'warehouse', 'date'], name='kardex_kard_present_2f3476_idx')],
            },
        ),
    ]
