# Generated by Django 5.2.7 on 2025-10-30 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemtax',
            name='line_item',
        ),
        migrations.DeleteModel(
            name='InvoiceLineItem',
        ),
        migrations.DeleteModel(
            name='LineItemTax',
        ),
    ]
