# Generated by Django 5.2.7 on 2025-10-30 04:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('productos', '0002_remove_lineitemtax_line_item_delete_invoicelineitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('posted', 'Emitida'), ('cancelled', 'Anulada')], default='draft', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal')),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Descuento')),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clientes.cliente', verbose_name='Cliente')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventario.warehouse', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='SKU de la presentación o producto', max_length=50, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('presentation_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de Presentación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Cantidad')),
                ('unit_of_measure', models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('m2', 'Metro Cuadrado'), ('m3', 'Metro Cúbico'), ('hour', 'Hora'), ('day', 'Día'), ('month', 'Mes'), ('package', 'Paquete')], max_length=20, verbose_name='Unidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Precio Unitario')),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], max_length=20, null=True, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor de Descuento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto de Descuento')),
                ('discount_reason', models.CharField(blank=True, max_length=255, verbose_name='Razón del Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Antes de impuestos', max_digits=15, verbose_name='Subtotal')),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Lote')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Serie')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='facturas.invoice', verbose_name='Factura')),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='productos.productpresentation', verbose_name='Presentación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='productos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('credit', 'Crédito')], max_length=20, verbose_name='Método')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Referencia')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='facturas.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Facturas',
            },
        ),
        migrations.CreateModel(
            name='LineItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(max_length=20, verbose_name='Tipo de Impuesto')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa (%)')),
                ('base', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Gravable')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_taxes', to='facturas.invoicelineitem', verbose_name='Línea de Factura')),
            ],
            options={
                'verbose_name': 'Impuesto de Línea',
                'verbose_name_plural': 'Impuestos de Líneas',
            },
        ),
    ]
