# Generated by Django 5.2.7 on 2025-10-29 17:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='RUC/NIT')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobada'), ('received', 'Recibida'), ('cancelled', 'Anulada')], default='draft', max_length=10, verbose_name='Estado')),
                ('order_date', models.DateField(verbose_name='Fecha de Orden')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal')),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventario.warehouse', verbose_name='Bodega')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='compras.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-order_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Descuento')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Impuesto')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Línea')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='productos.productpresentation', verbose_name='Presentación')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.purchaseorder', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Ítem de Orden de Compra',
                'verbose_name_plural': 'Ítems de Órdenes de Compra',
            },
        ),
    ]
